services:
  # 1. The Postgres 16 Database
  db:
    image: postgres:16-alpine
    container_name: tennis_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-tennis_analytics}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. pgAdmin (Visual tool to inspect the TML data)
  pgadmin:
    image: dpage/pgadmin4
    container_name: tennis_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False' # Optional: better for single-user
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - "8080:80"
    volumes:
      # Map the internal pgAdmin data to a local Docker volume
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  # 3. FastAPI Backend (The Engine)
  tennis_api:
    build: .
    container_name: tennis_api
    volumes:
      - .:/project
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-tennis_analytics}
      - PYTHONPATH=/project  # This ensures app.api.endpoints is found
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - THE_ODDS_API_KEY=${THE_ODDS_API_KEY}
    depends_on:
      - db
    # 🎯 Update the command line in your backend service
    command: gunicorn app.main:app --workers 2 --timeout 120 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    



  frontend:
    build: ./frontend
    container_name: tennis_ui
    working_dir: /project/frontend
    volumes:
      - ./frontend:/project/frontend
      - /project/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - tennis_api



  nginx:
    image: nginx:alpine
    container_name: tennis_proxy
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - tennis_api
      - frontend

  certbot:
    image: certbot/certbot
    container_name: tennis_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot



volumes:
  postgres_data:
  pgadmin_data:
