services:
  # 1. The Postgres 16 Database
  db:
    image: postgres:16-alpine
    container_name: tennis_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-tennis_analytics}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. pgAdmin (Visual tool to inspect the TML data)
  pgadmin:
    image: dpage/pgadmin4
    container_name: tennis_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # This allows pgAdmin to save settings without asking for a Master Password
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    ports:
      - "8080:80"
    volumes:
      # Map the internal pgAdmin data to a local Docker volume
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  # 3. FastAPI Backend (The Engine)
  tennis_api:
    build: .
    container_name: tennis_api
    volumes:
      - .:/project
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-tennis_analytics}
      - PYTHONPATH=/project  # This ensures app.api.endpoints is found
      - INTERNAL_API_KEY=${INTERNAL_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - THE_ODDS_API_KEY=${THE_ODDS_API_KEY}
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    dns:
      - 8.8.8.8
      - 8.8.4.4
    



  frontend:
    build: ./frontend
    container_name: tennis_ui
    volumes:
      - ./frontend:/project         # Syncs your code (src, etc.)
      - /project/node_modules       # <--- THIS IS THE FIX: Keeps node_modules INSIDE Docker only
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - tennis_api

volumes:
  postgres_data:
  pgadmin_data:
