"""adding matches played column to player_states

Revision ID: 1846143f59a3
Revises: 64f7ad060030
Create Date: 2026-03-15 12:02:45.496293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1846143f59a3'
down_revision: Union[str, None] = '64f7ad060030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_states', sa.Column('matches_played', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_states', 'matches_played')
    # ### end Alembic commands ###
