"""add_b365_ps_odds

Revision ID: 3da1b1f2a4da
Revises: 45dbe765d43e
Create Date: 2026-03-05 11:04:28.124318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da1b1f2a4da'
down_revision: Union[str, None] = '45dbe765d43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('b365_w', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('b365_l', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('ps_w', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('ps_l', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'ps_l')
    op.drop_column('matches', 'ps_w')
    op.drop_column('matches', 'b365_l')
    op.drop_column('matches', 'b365_w')
    # ### end Alembic commands ###
