"""create_upcoming_matches_table

Revision ID: 634da00e0faa
Revises: 940f7545c541
Create Date: 2026-03-05 20:41:07.699322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634da00e0faa'
down_revision: Union[str, None] = '940f7545c541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upcoming_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1_id', sa.String(), nullable=False),
    sa.Column('p2_id', sa.String(), nullable=False),
    sa.Column('p1_name', sa.String(), nullable=False),
    sa.Column('p2_name', sa.String(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('tournament', sa.String(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('b365_p1', sa.Float(), nullable=True),
    sa.Column('b365_p2', sa.Float(), nullable=True),
    sa.Column('ps_p1', sa.Float(), nullable=True),
    sa.Column('ps_p2', sa.Float(), nullable=True),
    sa.Column('predicted_p1_prob', sa.Float(), nullable=False),
    sa.Column('predicted_p2_prob', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['p1_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcoming_matches')
    # ### end Alembic commands ###
