"""add_winner_loser_embeddings

Revision ID: 686bbdb2833d
Revises: 1846143f59a3
Create Date: 2026-03-15 14:40:36.862597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '686bbdb2833d'
down_revision: Union[str, None] = '1846143f59a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('w_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matches', sa.Column('l_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'l_embedding')
    op.drop_column('matches', 'w_embedding')
    # ### end Alembic commands ###
