"""update_match_performance_stats

Revision ID: 8f444d4e7550
Revises: 44dbb1205c46
Create Date: 2026-03-04 09:22:29.741490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f444d4e7550'
down_revision: Union[str, None] = '44dbb1205c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('winner_ranking_points', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('loser_ranking_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'loser_ranking_points')
    op.drop_column('matches', 'winner_ranking_points')
    # ### end Alembic commands ###
