"""add_nn_p1_prob_to_matches

Revision ID: d30040c34450
Revises: 686bbdb2833d
Create Date: 2026-03-17 12:35:45.115897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30040c34450'
down_revision: Union[str, None] = '686bbdb2833d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('nn_p1_prob', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'nn_p1_prob')
    # ### end Alembic commands ###
