"""initial_string_id_schema

Revision ID: e183c55073bf
Revises: 
Create Date: 2026-03-03 18:26:48.733414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e183c55073bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('player', sa.String(length=150), nullable=False),
    sa.Column('atpname', sa.String(length=100), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('turnedpro', sa.Integer(), nullable=True),
    sa.Column('birthplace', sa.String(length=150), nullable=True),
    sa.Column('coaches', sa.String(length=255), nullable=True),
    sa.Column('hand', sa.String(length=20), nullable=True),
    sa.Column('backhand', sa.String(length=20), nullable=True),
    sa.Column('ioc', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_player'), 'players', ['player'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tourney_id', sa.String(length=50), nullable=False),
    sa.Column('tourney_name', sa.String(length=100), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('tourney_level', sa.String(length=10), nullable=False),
    sa.Column('tourney_date', sa.DateTime(), nullable=False),
    sa.Column('winner_id', sa.String(length=50), nullable=False),
    sa.Column('loser_id', sa.String(length=50), nullable=False),
    sa.Column('score', sa.String(length=100), nullable=False),
    sa.Column('best_of', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=10), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('w_ace', sa.Integer(), nullable=True),
    sa.Column('w_df', sa.Integer(), nullable=True),
    sa.Column('w_svpt', sa.Integer(), nullable=True),
    sa.Column('w_1stIn', sa.Integer(), nullable=True),
    sa.Column('w_1stWon', sa.Integer(), nullable=True),
    sa.Column('w_2ndWon', sa.Integer(), nullable=True),
    sa.Column('w_SvGms', sa.Integer(), nullable=True),
    sa.Column('w_bpSaved', sa.Integer(), nullable=True),
    sa.Column('w_bpFaced', sa.Integer(), nullable=True),
    sa.Column('winner_rank', sa.Integer(), nullable=True),
    sa.Column('l_ace', sa.Integer(), nullable=True),
    sa.Column('l_df', sa.Integer(), nullable=True),
    sa.Column('l_svpt', sa.Integer(), nullable=True),
    sa.Column('l_1stIn', sa.Integer(), nullable=True),
    sa.Column('l_1stWon', sa.Integer(), nullable=True),
    sa.Column('l_2ndWon', sa.Integer(), nullable=True),
    sa.Column('l_SvGms', sa.Integer(), nullable=True),
    sa.Column('l_bpSaved', sa.Integer(), nullable=True),
    sa.Column('l_bpFaced', sa.Integer(), nullable=True),
    sa.Column('loser_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_loser_id'), 'matches', ['loser_id'], unique=False)
    op.create_index(op.f('ix_matches_tourney_id'), 'matches', ['tourney_id'], unique=False)
    op.create_index(op.f('ix_matches_winner_id'), 'matches', ['winner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_winner_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_tourney_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_loser_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_players_player'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
